//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignPatterns
{
    using System;
    using System.Collections.Generic;
    
    public partial class maclar
    {
        public int macID { get; set; }
        public Nullable<int> homeID { get; set; }
        public Nullable<int> awayID { get; set; }
        public Nullable<int> hafta { get; set; }
        public Nullable<int> salonID { get; set; }
        public Nullable<int> basHakemID { get; set; }
        public Nullable<int> yHakemID { get; set; }
        public Nullable<int> iyHakemID { get; set; }
        public string ligAdi { get; set; }
    
        public virtual salonlar salonlar { get; set; }
        public virtual takimlar takimlar { get; set; }
        public virtual takimlar takimlar1 { get; set; }
        public virtual hakem hakem { get; set; }
    }
}
